apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recipe-frontend
  template:
    metadata:
      labels:
        app: recipe-frontend
    spec:
      containers:
        - name: frontend
          image: varunesht/auth-frontend:${BUILD_NUMBER}   # <-- Use Jenkins build number
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: recipe-frontend
spec:
  selector:
    app: recipe-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
